openapi: 3.1.0
info:
  title: Graeae Generation Test Host
  version: 1.0.0
paths:
  /hello:
    get:
      description: hello world
      responses:
        '200':
          description: okay
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
    post:
      description: hello world
      responses:
        '200':
          description: okay
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: name
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Person'
  /goodbye:
    get:
      description: goodbye world
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: okay
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      required:
        - name
        - age
