# https://github.com/marketplace/actions/publish-nuget
name: Publish STJ.OpenApi.Models
on:
  push:
    branches:
      - main
    paths:
      - 'OpenApi.Models/**/*'
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      # Publish
      - name: publish models
        id: publish_models
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: OpenApi.Models/OpenApi.Models.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY_FAKE}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: models-v*
      - name: archive packages
        uses: actions/upload-artifact@v2
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
