# https://github.com/marketplace/actions/publish-nuget
name: Publish Graeae.Models
on:
  push:
    branches:
      - main
    paths:
      - 'Graeae.AspNet.Analyzer/**/*'
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      # Publish
      - name: publish models
        id: publish_models
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Graeae.AspNet.Analyzer/Graeae.AspNet.Analyzer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_FORMAT: models-v*
          PACKAGE_NAME: Graeae.AspNet.Analyzer
      - name: archive packages
        uses: actions/upload-artifact@v4
        with:
          name: archive-packages
          path: |
            **/*.nupkg
            **/*.snupkg
